- name: Play 1
  hosts: localhost
  tasks:
    - name: execute command 'ls'
      changed_when: false
      command: ls

    - name: check if file exist
      stat: 
        path: /tmp/test.txt
      register: stat_file
    
    - debug:
        var: stat_file

    - name: create file on home dir
      command: touch /tmp/test.txt
      changed_when: not stat_file.stat.exists